spring.application.name=video-processor

# Configurações de Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Configurações do Bucket S3
aws.s3.bucket=${TF_BUCKET_NAME}
aws.region=${AWS_REGION}
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}

# Configurações de Notificação (Endpoint Externo)
notification.endpoint.url=${URL_MS_API}/api/capturas/update-status

#splitter secunds
splitter.interval-seconds=${SPLITTER_INTERVAL_SECONDS:10}


# Logging
logging.level.com.example.videoprocessor=DEBUG

# Configuração de Storage Local (Para testes)
storage.local.path=./capturas-validacao
