spring.application.name=video-processor

# Configurações de Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Configurações do Bucket S3
aws.s3.bucket=${TF_BUCKET_NAME}
aws.region=${AWS_REGION}
aws.sqs.queue-url=${SQS_QUEUE_URL}

# Configurações de Notificação (Endpoint Externo)
notification.endpoint.url=${URL_MS_API}/api/capturas/update-status

#splitter secunds
splitter.interval-seconds=${SPLITTER_INTERVAL_SECONDS:10}


# Logging
logging.level.com.example.videoprocessor=DEBUG

# Configuração de Storage Local (Para testes)
storage.local.path=./capturas-validacao

# Actuator/Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
